### ISSUE TITLE
CDU.py error

### ISSUE THREAD

**Issue by zbenesch** [y2kiah/A-10C-CDU-Display#1]
Hi,

I wanted to try this method, but after I installed everything step-by-step I get this error on bootup:
Traceback (most recent call last):
  File "/home/pi/CDUscreen/cdu.py", line 375, in <module>
    wrapper(main)
  File "/usr/lib/python3.5/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/pi/CDUscreen/cdu.py", line 307, in main
    curses.init_pair(Brt_Green, 10, curses.COLOR_BLACK)
_curses.error: init_pair() returned ERR

Then I get the bash simply. Any ideas why? Thanks in advance!

**Comment by y2kiah** [comment]
I would have to know more about the terminal you are trying to use to run and debug this. Are you running this headless over SSH or with a screen attached? For line 307 to fail, chances are your terminal does not support color. Check the return value of start_color and try calling has_colors and can_change_color to verify. See [https://linux.die.net/man/3/init_pair](https://linux.die.net/man/3/init_pair).

**Comment by zbenesch** [comment]
![image](https://user-images.githubusercontent.com/31964331/63220841-b3a61180-c18f-11e9-914f-f3440f8993e4.png)
Should be okay, am I wrong?

**Comment by zbenesch** [comment]
My setup is a basic 5" 800x480 lcd tft on a rpi 2 Model B rev 1.1, running raspbian LXterminal.
Everything else is from the readme in your guide.

Edit: I'm running this with the screen attached on boot, no keyboard or mouse.

**Comment by zbenesch** [comment]
So far troubleshooting got me this:
Set 
export TERM=linux
export TERMINFO=/etc/terminfo
TERM=xterm-256color

now it's failing with:
^Cpi@raspberrypi:~/CDUscreen $ python cdu.py
Traceback (most recent call last):
  File "cdu.py", line 375, in <module>
    wrapper(main)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "cdu.py", line 324, in main
    bus = init_MCP23017()
  File "cdu.py", line 284, in init_MCP23017
    bus.write_byte_data(DEVICE, IODIRA, 0x00)
IOError: [Errno 121] Remote I/O error


Which should suggest that the screen or the board is not connected properly, which is not the case, the screen is on and I can see the console.

**Comment by y2kiah** [comment]
The cdu.py script also handles the keypad matrix through the mcp23017 chip, which has nothing to do with the screen output itself. If you are only trying to implement the display, then comment out everything that has to do with the MCP chip. Also comment out anything regarding the Pi blaster library. That is only needed for handling PWM for LED back lighting.

You will also need to deploy a NodeRed project that I have not published yet to get the data export working. I haven't published it because there has been no interest in this project until now. let me know when you get to the point where you need it.

I am not using a Pi2 for NodeRed, I moved to a Pi3 because I found some pretty bad performance issues with certain features in the javascript engine used by Node.js on Pi2. The increased power of Pi3 handles the volume of data coming from DCS-BIOS flawlessly in NodeRed.

**Comment by zbenesch** [comment]
> The cdu.py script also handles the keypad matrix through the mcp23017 chip, which has nothing to do with the screen output itself. If you are only trying to implement the display, then comment out everything that has to do with the MCP chip. Also comment out anything regarding the Pi blaster library. That is only needed for handling PWM for LED back lighting.
> 
> You will also need to deploy a NodeRed project that I have not published yet to get the data export working. I haven't published it because there has been no interest in this project until now. let me know when you get to the point where you need it.
> 
> I am not using a Pi2 for NodeRed, I moved to a Pi3 because I found some pretty bad performance issues with certain features in the javascript engine used by Node.js on Pi2. The increased power of Pi3 handles the volume of data coming from DCS-BIOS flawlessly in NodeRed.

Yeah, I could see the problem with the p2, it will be too slow. 
At the first iteration I just want to make it work, the second will be the one I build in. 
Thanks for the heads up, I'll definitely buy a pi3 then.

I'll try to comment everything out and get back to you when I need the nodered project. 
Thanks!
